version: '3'
services:
  envoy:
    build:
      context: ./proxy
    container_name: envoy-grpc-proxy
    ports:
      - 9000:9000
  # client:
  #   build: ./client
  #   volumes:
  #     - ./client/src:/client/src
  #     - ./client/public:/client/public
  #   ports:
  #     - "3000:3000"
